# helloworld-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32060
  type: NodePort
  selector:
    app: helloworld